const SIGNAL_API='https://cmryhxnhnltrewvduico.supabase.co/functions/v1/doge-signal-api?key=0ZYgJdN_l2FdIeggiPq_uM49';
const PURCHASE_API='https://cmryhxnhnltrewvduico.supabase.co/functions/v1/doge-purchases-api';
const STORAGE_KEY='ace-doge-purchases-v1';
const SYNC_KEY='ace-doge-sync-code-v1';
const e=id=>document.getElementById(id);
const x={card:e('card'),signal:e('signal'),price:e('price'),change:e('change'),reason:e('reason'),refresh:e('refresh'),details:e('details'),score:e('score'),rsi:e('rsi'),sma20:e('sma20'),sma50:e('sma50'),range:e('range'),checks:e('checks'),updated:e('updated'),cloudStatus:e('cloudStatus'),syncCode:e('syncCode'),connectSync:e('connectSync'),generateSync:e('generateSync'),copySync:e('copySync'),disconnectSync:e('disconnectSync'),syncMessage:e('syncMessage'),storageLabel:e('storageLabel'),totalInvested:e('totalInvested'),totalDoge:e('totalDoge'),averagePrice:e('averagePrice'),currentValue:e('currentValue'),gainLoss:e('gainLoss'),logFive:e('logFive'),toggleCustom:e('toggleCustom'),customForm:e('customForm'),customAmount:e('customAmount'),purchaseNotice:e('purchaseNotice'),history:e('history'),purchaseCount:e('purchaseCount')};
let liveData=null;
let syncing=false;
let syncCode=localStorage.getItem(SYNC_KEY)||'';
let purchases=readLocal();

function money(v){v=Number(v);return Number.isFinite(v)?v<1?'$'+v.toFixed(5):'$'+v.toFixed(2):'—'}
function dollars(v){v=Number(v);return Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'—'}
function pct(v){v=Number(v);return Number.isFinite(v)?(v>=0?'+':'')+v.toFixed(2)+'%':'—'}
function uuid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random().toString(16).slice(2)}
function readLocal(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(value)?value.filter(p=>Number(p.amount)>0&&Number(p.price)>0).map(p=>({...p,clientId:p.clientId||p.client_id||p.id||uuid(),cloud:Boolean(p.cloud)})):[]}catch{return []}}
function saveLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(purchases.map(p=>({id:p.id,clientId:p.clientId,amount:p.amount,price:p.price,doge:p.doge,createdAt:p.createdAt,cloud:Boolean(p.cloud)}))))}
function formatWhen(value){return new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}
function generateCode(){const bytes=crypto.getRandomValues(new Uint8Array(18));const token=Array.from(bytes,b=>b.toString(36).padStart(2,'0')).join('').slice(0,28).toUpperCase();return 'ACE-'+token}
function setCloudStatus(label,mode=''){x.cloudStatus.className='cloud-status'+(mode?' '+mode:'');x.cloudStatus.innerHTML='<i></i>'+label}
function renderCloud(){x.syncCode.value=syncCode;x.storageLabel.textContent=syncCode?'Backed up in Supabase':'Phone only';x.copySync.disabled=!syncCode;x.disconnectSync.disabled=!syncCode;if(syncCode)setCloudStatus(syncing?'Syncing…':'Supabase backup active',syncing?'':'online');else setCloudStatus('Backup not connected')}

async function cloudRequest(action,payload={}){const response=await fetch(PURCHASE_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,syncCode,...payload})});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||'Cloud sync failed.');return data}
function cloudRow(row){return{id:row.id,clientId:row.client_id,amount:Number(row.amount_usd),price:Number(row.price_usd),doge:Number(row.doge_amount),createdAt:row.purchased_at,cloud:true}}

async function syncCloud(){if(syncing||!syncCode)return;syncing=true;renderCloud();x.syncMessage.textContent='Backing up and checking Supabase…';try{const local=readLocal().filter(p=>!p.cloud);if(local.length)await cloudRequest('upsert',{purchases:local});const data=await cloudRequest('list');purchases=(data.purchases||[]).map(cloudRow);saveLocal();renderPortfolio();x.syncMessage.textContent=local.length?local.length+' local purchase'+(local.length===1?' was':'s were')+' backed up in Supabase.':'Everything is backed up in Supabase.';setCloudStatus('Supabase backup active','online')}catch(error){setCloudStatus('Sync problem','error');x.syncMessage.textContent=error.message||'Could not sync.'}finally{syncing=false;renderCloud()}}

async function connectSync(){const next=x.syncCode.value.trim();if(next.length<16){x.syncMessage.textContent='Use a sync code with at least 16 characters.';return}syncCode=next;localStorage.setItem(SYNC_KEY,syncCode);renderCloud();await syncCloud()}
function makeNewSync(){syncCode=generateCode();localStorage.setItem(SYNC_KEY,syncCode);renderCloud();x.syncMessage.textContent='New private sync code created. Copy it somewhere safe.';syncCloud()}
async function copySync(){if(!syncCode)return;try{await navigator.clipboard.writeText(syncCode);x.syncMessage.textContent='Sync code copied. Keep it private.'}catch{x.syncMessage.textContent='Press and hold the code to copy it.'}}
function disconnectSync(){if(!syncCode||!confirm('Disconnect this phone from the Supabase backup? Your cloud records will stay safe.'))return;localStorage.removeItem(SYNC_KEY);syncCode='';purchases=purchases.map(p=>({...p,cloud:false}));saveLocal();renderCloud();renderPortfolio();x.syncMessage.textContent='This phone is disconnected. Enter the same code later to restore your cloud history.'}

function safe(message){liveData=null;x.card.className='signal wait';x.signal.textContent='WAIT';x.price.textContent='—';x.change.textContent='Live data unavailable';x.change.className='change negative';x.reason.textContent=message||'The live market feed could not be checked safely.';x.details.classList.add('hidden');x.updated.textContent='No purchase signal is shown without verified live data.';x.logFive.disabled=true;x.purchaseNotice.textContent='Live price is unavailable, so purchase logging is paused to avoid recording the wrong price.';renderPortfolio()}
function renderSignal(d){liveData=d;const buy=d.signal==='BUY SMALL';x.card.className='signal '+(buy?'buy':'wait');x.signal.textContent=d.signal||'WAIT';x.price.textContent=money(d.price);x.change.textContent=pct(d.change24h)+' today';x.change.className='change '+(Number(d.change24h)>=0?'positive':'negative');x.reason.textContent=d.reason||'The board recommends waiting.';x.score.textContent=d.score+' / 4';x.rsi.textContent=Number(d.rsi14).toFixed(1);x.sma20.textContent=money(d.sma20);x.sma50.textContent=money(d.sma50);x.range.textContent=money(d.sevenDayLow)+' – '+money(d.sevenDayHigh);x.checks.replaceChildren(...(d.checks||[]).map(c=>{const li=document.createElement('li'),b=document.createElement('b');li.className=c.passed?'passed':'notpassed';b.textContent=c.passed?'✓':'○';li.append(b,document.createTextNode(c.label));return li}));x.details.classList.remove('hidden');x.updated.textContent='Updated '+new Date(d.updatedAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles',dateStyle:'medium',timeStyle:'short'})+' Pacific.';x.logFive.disabled=false;x.purchaseNotice.textContent='Tap “Log this $5 purchase” to save it at the current displayed price of '+money(d.price)+'.';renderPortfolio()}
async function loadSignal(){x.refresh.disabled=true;x.refresh.textContent='Checking…';try{const r=await fetch(SIGNAL_API+'&t='+Date.now(),{cache:'no-store'}),d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'The signal service is unavailable.');renderSignal(d)}catch(err){safe(err.message)}finally{x.refresh.disabled=false;x.refresh.textContent='Check again'}}

async function addPurchase(amount){amount=Number(amount);const price=Number(liveData&&liveData.price);if(!Number.isFinite(amount)||amount<=0)return alert('Enter a valid dollar amount.');if(!Number.isFinite(price)||price<=0)return alert('Wait for a verified live DOGE price first.');const clientId=uuid(),createdAt=new Date().toISOString();if(syncCode){x.purchaseNotice.textContent='Saving securely to Supabase…';try{const data=await cloudRequest('add',{clientId,amount:Number(amount.toFixed(2)),price,createdAt});purchases.unshift(cloudRow(data.purchase));saveLocal();renderPortfolio();x.purchaseNotice.textContent=dollars(amount)+' purchase backed up in Supabase at '+money(price)+'.'}catch(error){x.purchaseNotice.textContent='Could not back up purchase: '+error.message}}else{purchases.unshift({id:clientId,clientId,amount:Number(amount.toFixed(2)),price,doge:amount/price,createdAt,cloud:false});saveLocal();renderPortfolio();x.purchaseNotice.textContent=dollars(amount)+' saved on this phone. Connect Supabase above to back it up.'}}
async function deletePurchase(id){const item=purchases.find(p=>p.id===id);if(!item||!confirm('Remove this '+dollars(item.amount)+' purchase from the tracker?'))return;if(item.cloud&&syncCode){try{await cloudRequest('delete',{id})}catch(error){return alert('Could not remove the cloud record: '+error.message)}}purchases=purchases.filter(p=>p.id!==id);saveLocal();renderPortfolio()}
function renderPortfolio(){const invested=purchases.reduce((sum,p)=>sum+Number(p.amount||0),0),doge=purchases.reduce((sum,p)=>sum+Number(p.doge||0),0),average=doge>0?invested/doge:NaN,currentPrice=Number(liveData&&liveData.price),value=Number.isFinite(currentPrice)?doge*currentPrice:NaN,gain=Number.isFinite(value)?value-invested:NaN;x.totalInvested.textContent=dollars(invested);x.totalDoge.textContent=doge.toLocaleString('en-US',{maximumFractionDigits:2})+' Ð';x.averagePrice.textContent=Number.isFinite(average)?money(average):'—';x.currentValue.textContent=Number.isFinite(value)?dollars(value):'—';x.gainLoss.textContent=Number.isFinite(gain)?(gain>=0?'+':'')+dollars(gain).replace('$','')+' ('+(invested>0?pct(gain/invested*100):'+0.00%')+')':'—';x.gainLoss.className=Number.isFinite(gain)?(gain>=0?'gain':'loss'):'';x.purchaseCount.textContent=purchases.length+' purchase'+(purchases.length===1?'':'s');if(!purchases.length){x.history.innerHTML='<div class="empty">No purchases have been logged yet.</div>';return}x.history.replaceChildren(...purchases.map(p=>{const row=document.createElement('article');row.className='purchase';const left=document.createElement('div'),title=document.createElement('h4'),meta=document.createElement('p');title.textContent=dollars(p.amount)+' buy';meta.textContent=formatWhen(p.createdAt)+' · '+money(p.price)+' per DOGE · '+(p.cloud?'Supabase':'Phone only');left.append(title,meta);const side=document.createElement('div'),quantity=document.createElement('strong'),remove=document.createElement('button');side.className='purchase-side';quantity.textContent=Number(p.doge).toLocaleString('en-US',{maximumFractionDigits:2})+' Ð';remove.className='delete';remove.type='button';remove.textContent='Remove';remove.addEventListener('click',()=>deletePurchase(p.id));side.append(quantity,remove);row.append(left,side);return row}))}

x.refresh.addEventListener('click',loadSignal);x.logFive.addEventListener('click',()=>addPurchase(5));x.toggleCustom.addEventListener('click',()=>{x.customForm.classList.toggle('hidden');if(!x.customForm.classList.contains('hidden'))x.customAmount.focus()});x.customForm.addEventListener('submit',event=>{event.preventDefault();addPurchase(x.customAmount.value);x.customAmount.value='';x.customForm.classList.add('hidden')});x.connectSync.addEventListener('click',connectSync);x.generateSync.addEventListener('click',makeNewSync);x.copySync.addEventListener('click',copySync);x.disconnectSync.addEventListener('click',disconnectSync);
if(!syncCode){syncCode=generateCode();localStorage.setItem(SYNC_KEY,syncCode);x.syncMessage.textContent='A private sync code was created automatically. Copy it somewhere safe.'}renderCloud();renderPortfolio();loadSignal();syncCloud();